### PR TITLE
Make sure ifup is scheduled

### PR DESCRIPTION
**Pull request by nadvornik**

### CODE REVIEW

**Comment by nadvornik** [comment]
@lkotek Can you please confirm that it fixes bsc 1173149 ?

**Comment by lkotek** [comment]
@nadvornik Sorry I was busy with Ubuntu 20.04 testing. I will confirm this today.

**Comment by lkotek** [comment]
@nadvornik Script doesn't seem to be included at generated initrd.

**Comment by lkotek** [comment]
Successfully tested with different terminal than the one, which was originally used.

Terminal was able to obtain IPv4 address and boot via wifi as expected.

**Pull request merged**
