### PR TITLE
Fix image name in POS_Image-RPi-Bootstrap.kiwi

### PR DESCRIPTION
**Pull request by nadvornik**

### CODE REVIEW

**Review by juliogonzalez — APPROVED** [review]
LGTM

**Comment by aaannz** [comment]
@juliogonzalez This was not yet submitted to release channels, right? I am wondering if changelog is required or just this change is enough.

**Comment by juliogonzalez** [comment]
@aaannz not submitted yet. No need for changes at the changelog or the SPEC :-)

**Review by aaannz — APPROVED** [review]

**Comment by juliogonzalez** [comment]
Remember to create a PR for D:G:M:H, and I will handle it :-)

**Pull request merged**
