### PR TITLE
Use more reliable progress output

### PR DESCRIPTION
**Pull request by nadvornik**

### CODE REVIEW

**Comment by nadvornik** [comment]
openqa test looks good

**Comment by nadvornik** [comment]
Do we need this fix also for sle12 images? I have not seen any failure there.

**Comment by aaannz** [comment]
I'm not sure. Both kiwi-desc-saltboot and dracut-saltboot uses start_event_grains so the speedup may be the same and result in similar problems. Is there any drawback for this solution?

**Comment by nadvornik** [comment]
I don't see any drawback, I will add it.

**Pull request merged**
