### PR TITLE
Add FQDN as an option as minion id

### PR DESCRIPTION
**Pull request by aaannz**
- introduce USE_FQDN_MINION_ID kernel command line option to control
  if plain hostname (if not set) or full FQDN (if set) should be used
  for minion id. This is in effect only if terminal IP is reverse
  resolvable
- introduce DISABLE_ID_PREFIX kernel command line option to control
  if BRANCH_ID should be prefixed (if not set) to the minion id or
  not (if set)

### CODE REVIEW

**Comment by aaannz** [comment]
CC @Bischoff This makes a little change in configuration. It adds branch_id to the branch network form. I'll create a new PR for PXE formula which will remove the option from that form. Together with changes in other PXE formula it will provide support to have FQDN as a minion od. As mentioned in https://github.com/SUSE/spacewalk/issues/10515

**Comment by Bischoff** [comment]
> CC @Bischoff This makes a little change in configuration. It adds branch_id to the branch network form. I'll create a new PR for PXE formula which will remove the option from that form. Together with changes in other PXE formula it will provide support to have FQDN as a minion od. As mentioned in [SUSE/spacewalk#10515](https://github.com/SUSE/spacewalk/issues/10515)

OK.

Did you see my (weird) idea about a format string ?

**Comment by aaannz** [comment]
> Did you see my (weird) idea about a format string ?

Yes, I tried to do it that way, but the code looked weird and was wondering what is the real value. Given customer can use Hostnames, it is possible to do various names through DNS.

**Comment by Bischoff** [comment]
> > Did you see my (weird) idea about a format string ?
> 
> Yes, I tried to do it that way, but the code looked weird and was wondering what is the real value. Given customer can use Hostnames, it is possible to do various names through DNS.

Yes, that was probably difficult to implement, I agree. Also agree with the remark about doing it at DNS level.

**Comment by aaannz** [comment]
@nadvornik I added the fixes for retail cli tools. Without this the retail_yaml dump would fail. The format of yaml is not changed.

**Comment by aaannz** [comment]
Test suite passed - http://sleposbuilder.suse.cz/tests/5930

**Pull request merged**
