### PR TITLE
Add autodiscovery code for salt partitions

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by aaannz** [comment]
This is just a quick idea, maybe I can add code checking for branch id prefix difference and based on it ask for reregister?

**Comment by aaannz** [comment]
WDYT? @nadvornik

**Comment by nadvornik** [comment]
The code is OK.

I am not sure about the ratio of cases where this is desired behavior and cases where new deployment is wanted.

**Comment by aaannz** [comment]
> I am not sure about the ratio of cases where this is desired behavior and cases where new deployment is wanted.

Yeah, me neither. I was just thing if this can simplify pxe database problem in some way.

**Comment by aaannz** [comment]
Going in different direction. Closing.

**Pull request closed without merging**
